import React from 'react';

export const metadata = {
    title: "Next App | About",
    description: "Generated by create next app",
  };

const page = () => {
    return (
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
            This is about the website.
        </div>
    );
};

export default page;