import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/SharedComponents/NavBar";
import Footer from "@/Components/SharedComponents/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
